name: Addition_Reusable_workflow
on: 
 workflow_call:
  inputs:
   number1:
    description: 'Enter first number'     
    required: true
    type: number
   number2:
    description: 'Enter second number'     
    required: true  
    type: number

  
#env:
 #number1: ${{ inputs.number1 }}
# number2: ${{ inputs.number2 }}

jobs:
 addition:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v3
   - id: step1
     run: |
      echo "Add two numbers ${{ inputs.number1 }} and  ${{ inputs.number2 }}"
      sum=`expr ${{ inputs.number1 }} + ${{ inputs.number2 }} `
      echo "summation=$sum"
