name: caller_workflow
on: 
 workflow_dispatch:
  inputs:
   number1:
    description: 'Enter first number'     
    required: true
   number2:
    description: 'Enter second number'     
    required: true
env:
 number1: ${{ github.event.inputs.number1 }}
 number2: ${{ github.event.inputs.number2 }}

jobs:
 calling-test-job:
  uses: goyal20nikita/ReusableWorkflow/.github/workflows/test.yaml@main
 calling-addition-job:
  uses: goyal20nikita/ReusableWorkflow/.github/workflows/addition.yaml@main
  with:
   number1: ${{env.number1}}
   number2: ${{env.number2}}
 calling-subtraction-job:
  uses: goyal20nikita/ReusableWorkflow/.github/workflows/subtraction.yaml@main
  with:
   number1: 4
   number2: 3
