name: caller_workflow
on: 
 workflow_dispatch:


jobs:
 calling-test-job:
  uses: goyal20nikita/ReusableWorkflow/.github/workflows/test.yaml@main
 calling-from-other-account-repo-job:
  uses: goyal20nikita/ReusableWorkflow/.github/workflows/addition.yaml@main
  with:
   number1: 4
   number2: 3
 calling-from-own-repository-job:
  uses: harshmittal-cyber/newcompositeworkflow/.github/workflows/addition.yml@main
  with:
   number1: 6
   number2: 3
