name: caller_workflow
on: 
 workflow_dispatch:
  inputs:
   number1:
    description: 'Enter first number'     
    required: true
   number2:
    description: 'Enter second number'     
    required: true
env:
 number1: ${{ github.event.inputs.number1 }}
 number2: ${{ github.event.inputs.number2 }}

jobs:
 calling-addition-job:
  uses: goyal20nikita/ReusableWorkflow/.github/workflows/addition.yml@main
  with:
   number1: 2
   number2: 4
 calling-subtraction-job:
  uses: goyal20nikita/ReusableWorkflow/.github/workflows/subtraction.yml@main
  with:
   number1: 4
   number2: 3
