name: subtraction_Reusable_workflow2
on: 
 workflow_call:
  inputs:
   number1:
    description: 'Enter first number'     
    required: true
    type: number
   number2:
    description: 'Enter second number'     
    required: true  
    type: number
  outputs:
   sum:
     description: "addition value"
     value: ${{ jobs.subtraction.outputs.output1 }}
  
#env:
 #number1: ${{ inputs.number1 }}
# number2: ${{ inputs.number2 }}

jobs:
 subtraction:
   runs-on: ubuntu-latest
   outputs:
      output1: ${{ steps.step1.outputs.subtraction }}
   steps:
   - uses: actions/checkout@v3
   - id: step1
     run: |
      echo "subtract two numbers ${{ inputs.number1 }} and  ${{ inputs.number2 }}"
      subtract=`expr ${{ inputs.number1 }} - ${{ inputs.number2 }} `
      echo "subtraction=$subtract"
